ifeq ($(CONFIG_OPPO_FINGERPRINT),y)
obj-y        += egis/
obj-y        += fpc/
obj-y        += goodix_fp/
obj-y        += goodix_optical_fp/
obj-y        += oppo_fp_common/
obj-y        += silead/
obj-y        += silead_optical_fp/
endif

subdir-ccflags-y += -DCONFIG_OPPO_FINGERPRINT_PROJCT=19651
