#ifdef CONFIG_PRODUCT_REALME_SDM710
#wen.luo@PSW.Kernel.MM, 2018/05/23, Add for Healthinfo monitor
obj-$(CONFIG_OPPO_SHUTDOWN_DETECT)	+=  oppo_shutdown_detect.o
#endif /* CONFIG_PRODUCT_REALME_SDM710 */
